// 生成高质量的种子数据 ideas.json
// 包含知乎模拟数据 + 精选海外产品样本
const fs = require('fs');
const path = require('path');

const OUTPUT = path.join(__dirname, '../public/data/ideas.json');

// 今天和最近几天的日期
const today = new Date().toISOString().slice(0, 10);
const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
const twoDaysAgo = new Date(Date.now() - 2 * 86400000).toISOString().slice(0, 10);

// ─── 知乎：传统需求的直接声音 ─────────────────────────────────────────────
const zhihuItems = [
  {
    id: 'zhihu-zh001', title: 'Excel管理数据太繁琐，多人协作经常出错',
    problem: '中小企业用 Excel 做库存/客户/财务管理，多人编辑文件冲突、数据丢失是家常便饭，老板看不到实时数据',
    solution: '轻量在线数据库：表单录入+自动汇总+权限控制，手机端实时查看，比 Excel 简单，比飞书多维表格便宜',
    score: 5, chinaFit: 'high', chinaReason: '国内中小企业数字化需求强，现有工具要么太贵要么太重',
    soloFit: 'yes', soloReason: '功能边界清晰，微信小程序+SaaS 一人 2 个月可完成 MVP',
    techStack: ['Next.js', '微信小程序', 'Supabase', 'Vercel'], devTimeline: '1-3月',
    mvp: '先做单一业务的数据录入+看板，目标 1 个垂直行业，4 周上线',
    coldStart: '行业协会微信群/抖音行业号推广，免费版换口碑，付费版解锁数据导出',
    dateKey: today, source: 'zhihu', sourceLabel: '知乎',
  },
  {
    id: 'zhihu-zh002', title: '小微企业客户跟进混乱，用微信管客户太累',
    problem: '销售用微信聊客户，报价单、沟通记录、合同全散落在对话里，新人交接完全摸不清头绪，漏单率极高',
    solution: '微信优先的轻量 CRM：一键把微信对话同步到客户档案，自动触发跟进提醒，业绩看板实时更新',
    score: 5, chinaFit: 'high', chinaReason: '国内销售场景高度依赖微信，与微信深度集成的轻量 CRM 几乎是空白',
    soloFit: 'yes', soloReason: '核心功能清晰，微信集成有 API，3 个月可完成完整产品',
    techStack: ['Next.js', '微信 API', 'Supabase', 'Vercel'], devTimeline: '1-3月',
    mvp: '手动录入客户+跟进记录的最简 CRM，先验证用户粘性',
    coldStart: '销售培训类微信群、企业微信生态推广，找 20 个种子用户免费用',
    dateKey: today, source: 'zhihu', sourceLabel: '知乎',
  },
  {
    id: 'zhihu-zh003', title: '每次开会都要手动记录，行动项经常丢失',
    problem: '每次会议结束行动项靠手动记录，下次开会前没人知道上次决定了什么，反复对齐消耗大量时间',
    solution: '会议 AI 助手：自动录音转文字→提取行动项→分配责任人→发送跟进提醒，会后 5 分钟生成完整纪要',
    score: 4, chinaFit: 'high', chinaReason: '企业会议频繁，飞书等工具太重，轻量会议 AI 有明确需求',
    soloFit: 'yes', soloReason: 'Whisper+大模型可快速集成，3 个月可完成核心功能',
    techStack: ['Next.js', 'Whisper API', 'OpenAI API', 'Supabase'], devTimeline: '1-3月',
    mvp: '上传会议录音→输出行动项列表，先验证准确率和付费意愿',
    coldStart: '投递给中小企业 CEO 微信群，展示真实会议纪要效果，口碑传播',
    dateKey: today, source: 'zhihu', sourceLabel: '知乎',
  },
  {
    id: 'zhihu-zh004', title: '小零售店库存靠纸质台账，盘点耗时耗力',
    problem: '小零售店/仓库靠纸质台账管库存，盘点耗一整天，经常卖出去没记、进货漏登，导致断货或积压',
    solution: '手机扫码入出库，库存实时同步云端，低库存自动预警+生成补货单，老板手机随时查看',
    score: 4, chinaFit: 'high', chinaReason: '国内小店数量庞大，数字化工具普及率低，价格敏感但需求真实',
    soloFit: 'yes', soloReason: '功能简单，微信小程序+SaaS 模式，2 个月可完成 MVP',
    techStack: ['微信小程序', 'Supabase', 'Node.js', 'Vercel'], devTimeline: '1-3月',
    mvp: '扫码入出库+实时库存表，月费 ¥29，目标便利店/小超市',
    coldStart: '批发市场/商圈地推，提供 1 个月免费试用，帮店主一对一上手',
    dateKey: yesterday, source: 'zhihu', sourceLabel: '知乎',
  },
  {
    id: 'zhihu-zh005', title: '传统餐饮高峰期点单效率太低，翻台慢',
    problem: '高峰期服务员忙不过来，顾客等太久不耐烦，纸质点单传到厨房容易出错，翻台慢直接影响营业额',
    solution: '扫码点餐小程序：顾客自助下单→后厨大屏实时显示→出餐后自动通知，减少服务员来回走动 70%',
    score: 5, chinaFit: 'high', chinaReason: '国内餐饮数量庞大，美团等方案抽佣高，独立工具有替代空间',
    soloFit: 'yes', soloReason: '微信小程序扫码点餐是成熟方案，2-3 个月可完成包含支付的完整产品',
    techStack: ['微信小程序', '微信支付', 'Supabase', 'Node.js'], devTimeline: '1-3月',
    mvp: '扫码点餐+微信支付+后厨打印，月费 ¥99，目标 50 人以下中小餐厅',
    coldStart: '本地餐饮协会/商圈切入，免费帮 3 家店上线换案例，口碑推广',
    dateKey: yesterday, source: 'zhihu', sourceLabel: '知乎',
  },
  {
    id: 'zhihu-zh006', title: '接多个项目的自由职业者时间管理混乱',
    problem: '接多个项目的自由职业者同时面对多个甲方催促，不知道优先做什么，经常为了赶一个耽误另一个',
    solution: '多项目时间块管理：可视化分配不同项目工时，AI 根据截止日期自动排优先级，发送每日计划',
    score: 4, chinaFit: 'high', chinaReason: '国内自由职业者数量快速增长，现有工具要么太重要么不适配多项目场景',
    soloFit: 'yes', soloReason: '工具型产品，核心功能 2 个月可完成，类 Notion 轻量版',
    techStack: ['Next.js', 'Supabase', 'Tailwind CSS', 'Vercel'], devTimeline: '1-3月',
    mvp: '项目列表+时间块日历，支持微信提醒，月费 ¥19，目标设计/开发类自由职业者',
    coldStart: '在 Behance/站酷/BOSS 直聘等自由职业者社区发帖推广',
    dateKey: yesterday, source: 'zhihu', sourceLabel: '知乎',
  },
  {
    id: 'zhihu-zh007', title: '小型健身房会员管理混乱，课时对不上号',
    problem: '健身房前台用 Excel 记会员档案，会员到期忘提醒，私教课次数对不上，纠纷频发影响口碑',
    solution: '会员管理小程序：入场扫码核验，私教课次数自动扣减，到期前 7 天自动发微信提醒续费',
    score: 3, chinaFit: 'high', chinaReason: '国内中小健身房数量多，管理软件要么太贵要么体验差',
    soloFit: 'yes', soloReason: '功能边界清晰，3 个月可完成包含微信支付的完整 MVP',
    techStack: ['微信小程序', '微信支付', 'Supabase', 'Node.js'], devTimeline: '1-3月',
    mvp: '会员档案+课次管理+到期提醒，月费 ¥99，目标 200 人以下小健身房',
    coldStart: '健身房店主微信群/抖音健身行业号，免费试用 30 天换口碑',
    dateKey: twoDaysAgo, source: 'zhihu', sourceLabel: '知乎',
  },
  {
    id: 'zhihu-zh008', title: '小团队进度汇报全靠微信，信息极易丢失',
    problem: '小团队用微信群汇报进度，信息淹没在聊天记录里，项目经理每天逐一追问，协作效率极低',
    solution: '轻量看板+自动日报：成员更新任务状态，系统自动归纳每日进展发到群里，管理者无需主动追问',
    score: 4, chinaFit: 'high', chinaReason: '国内中小团队大量使用微信协作，Jira 太重，飞书任务太复杂',
    soloFit: 'yes', soloReason: '轻量看板是成熟方案，2 个月可完成 + 微信推送集成',
    techStack: ['Next.js', '企业微信 API', 'Supabase', 'Vercel'], devTimeline: '1-3月',
    mvp: '看板+每日自动日报推送，5 人以内免费，6 人以上月费 ¥99',
    coldStart: '程序员/设计师社群发帖，抓住"团队协作太乱"的痛点吸引种子用户',
    dateKey: twoDaysAgo, source: 'zhihu', sourceLabel: '知乎',
  },
];

// ─── 精选海外产品样本（Product Hunt / Reddit / TrustMRR）─────────────────
const overseasItems = [
  {
    id: 'ph-sample-001',
    title: 'AI Video Generator for E-commerce',
    problem: '电商卖家需要大量短视频素材投流，拍摄+剪辑成本高，外包质量不稳定且响应慢，新品上线延误',
    solution: '输入产品图片和卖点文案，AI 自动合成带口播的竖版短视频，批量生产投流素材，成本降低 80%',
    score: 5, chinaFit: 'high', chinaReason: '国内电商卖家对投流视频素材需求爆发，可灵/即梦已验证市场，垂直电商场景工具仍稀缺',
    soloFit: 'maybe', soloReason: '需集成视频生成 API，3-6 个月完成，核心是调好视频生成质量',
    techStack: ['Next.js', 'Kling/Runway API', 'Cloudflare R2', 'Vercel'], devTimeline: '3-6月',
    mvp: '上传产品图+卖点文字→生成 15 秒竖版视频，按条收费 ¥9.9，先跑电商卖家群',
    coldStart: '淘宝/拼多多卖家微信群直接推广，提供 3 条免费试用视频',
    url: 'https://www.producthunt.com', source: 'producthunt', sourceLabel: 'Product Hunt',
    dateKey: today, tags: ['AI', '视频', '电商'], category: 'AI工具',
  },
  {
    id: 'ph-sample-002',
    title: 'AI Meeting Transcription & Action Items',
    problem: '会议/播客录音转文字靠人工，一小时音频要花 3-4 小时逐字听写，且专业术语识别不准确',
    solution: 'Whisper 模型本地化+专业词库，识别准确率 95%+，自动提取行动项分配责任人，会后 5 分钟出纪要',
    score: 4, chinaFit: 'high', chinaReason: '国内企业会议频繁，飞书等方案贵且绑定生态，独立轻量工具有市场',
    soloFit: 'yes', soloReason: '调用 Whisper API 集成，核心功能 6 周可完成，服务小团队',
    techStack: ['Next.js', 'Whisper API', 'GPT-4o', 'Supabase'], devTimeline: '1-3月',
    mvp: '上传音频→下载带时间轴的文字稿+行动项，前 3 次免费，之后按小时收费 ¥9.9',
    coldStart: '企业微信/钉钉群推广，产品经理/运营社群精准投放',
    url: 'https://www.producthunt.com', source: 'producthunt', sourceLabel: 'Product Hunt',
    dateKey: today, tags: ['AI', '效率', '会议'], category: 'AI工具',
  },
  {
    id: 'tmrr-sample-001',
    title: 'Invoice & Billing Tool for Freelancers',
    problem: '自由职业者/小工作室用 Excel 手动开账单，跟催款项靠微信提醒，不专业且财务一团混乱',
    solution: '一键生成专业报价单/账单，自动发送付款提醒，在线收款+记账全流程打通，账期一目了然',
    score: 5, chinaFit: 'high', chinaReason: '国内自由职业者和小工作室数量庞大，微信收款+手工对账是普遍痛点，付费意愿强',
    soloFit: 'yes', soloReason: '表单+PDF 生成+微信支付集成，2 个月完成 MVP，功能边界清晰',
    techStack: ['Next.js', '微信支付', 'Supabase', 'Vercel'], devTimeline: '1-3月',
    mvp: '创建账单+一键发送微信/邮件+记录收款状态，月费 ¥29，目标设计师/程序员自由职业',
    coldStart: '设计师社群（站酷/Behance）+ 程序员群推广，提供 30 天免费试用',
    url: 'https://trustmrr.com', source: 'trustmrr', sourceLabel: 'TrustMRR',
    mrr: '$8.5K MRR', dateKey: today, tags: ['已验证收入', '财务', '自由职业'], category: '财务工具',
  },
  {
    id: 'reddit-sample-001',
    title: 'Solo Founder Built SEO Content Tool to $5K MRR',
    problem: '独立站/博客靠 SEO 获客，但写一篇高质量长文需要 4-8 小时，更新频率上不去，流量增长停滞',
    solution: '关键词输入→大纲生成→全文写作→内链建议，一条 SEO 文章 15 分钟产出，可批量操作',
    score: 5, chinaFit: 'mid', chinaReason: '百度 SEO 与 Google 逻辑不同，需专门做百度/小红书搜索优化版本',
    soloFit: 'yes', soloReason: '调用 GPT/Claude API + 关键词分析，2 个月完成核心功能',
    techStack: ['Next.js', 'OpenAI API', 'Supabase', 'Vercel'], devTimeline: '1-3月',
    mvp: '输入关键词→生成 1500 字 SEO 文章，免费 3 篇，付费 ¥59/月无限制',
    coldStart: '在 V2EX/独立开发者群发布，SEO 博客写真实测评结果吸引长尾流量',
    url: 'https://www.reddit.com/r/SaaS', source: 'reddit', sourceLabel: 'r/SaaS',
    mrr: '$5K MRR', dateKey: today, tags: ['已验证收入', 'SEO', 'AI写作'], category: 'AI工具',
  },
  {
    id: 'reddit-sample-002',
    title: 'Cold Email Automation for B2B Outreach',
    problem: 'B2B 销售手动写外联邮件，每封邮件个性化耗时 10 分钟，每天只能触达 20-30 人，新客开发极慢',
    solution: '抓取潜客 LinkedIn 资料→大模型生成个性化邮件序列→自动追踪打开率和回复，一人完成 SDR 工作量',
    score: 4, chinaFit: 'high', chinaReason: '出海 B2B 企业和外贸公司强需求，国内对应工具几乎空白，可直接本土化',
    soloFit: 'yes', soloReason: '邮件发送 + AI 文案生成，核心逻辑 2 个月可完成，API 成熟',
    techStack: ['Next.js', 'OpenAI API', 'Resend', 'Supabase'], devTimeline: '1-3月',
    mvp: '导入 CSV 潜客列表，自动生成 3 封邮件序列，追踪打开率，按联系人数量收费',
    coldStart: '外贸/出海企业微信群精准投放，提供 50 条免费额度验证效果',
    url: 'https://www.reddit.com/r/microsaas', source: 'reddit', sourceLabel: 'r/microsaas',
    dateKey: yesterday, tags: ['B2B', '销售', '邮件自动化'], category: '营销增长',
  },
  {
    id: 'hn-sample-001',
    title: 'Show HN: AI-powered contract review for small businesses',
    problem: '创业者签合同靠直觉或找律师，律师费动辄数千，小额合同明显不划算，常被不平等条款坑',
    solution: '上传合同→AI 高亮风险条款→逐条解释并给出修改建议，5 分钟完成人工需 2 小时的审阅',
    score: 4, chinaFit: 'high', chinaReason: '国内中小企业合同风险意识提升，但法律资源昂贵，AI 合同审阅有真实需求',
    soloFit: 'yes', soloReason: 'PDF 解析+大模型推理，核心功能 6 周可完成，无需复杂基础设施',
    techStack: ['Next.js', 'Claude API', 'Supabase', 'Vercel'], devTimeline: '1-3月',
    mvp: '上传 PDF 合同→高亮风险段落+解释，免费审阅 1 份，付费 ¥29/份 或 ¥99/月无限制',
    coldStart: '创业者社群/法律知识博主合作，内容营销展示真实审阅案例吸引用户',
    url: 'https://news.ycombinator.com', source: 'hackernews', sourceLabel: 'Hacker News',
    dateKey: yesterday, tags: ['AI', '法律', 'B2B'], category: 'AI工具',
  },
  {
    id: 'tmrr-sample-002',
    title: 'Website Uptime Monitor with WeChat Alerts',
    problem: '独立开发者网站宕机往往几小时后才发现，错过修复黄金期，用户已经流失并留下差评',
    solution: '全球节点每分钟探测，宕机 30 秒内微信/钉钉推送，附带性能瀑布图定位慢节点，历史可用率报告',
    score: 4, chinaFit: 'high', chinaReason: '国内独立开发者和小团队数量增长，微信/钉钉告警比邮件更符合中国使用习惯',
    soloFit: 'yes', soloReason: 'Vercel Edge + Cron 构建探测系统，微信推送 API 成熟，6 周可完成',
    techStack: ['Next.js', 'Vercel Edge', 'Supabase', '微信推送 API'], devTimeline: '1-3月',
    mvp: '免费版监控 3 个网站+微信推送，收费版 ¥29/月 不限数量+历史报表',
    coldStart: '独立开发者社群（V2EX/HelloGitHub）发布，解决真实痛点自然口碑',
    url: 'https://trustmrr.com', source: 'trustmrr', sourceLabel: 'TrustMRR',
    mrr: '$3.2K MRR', dateKey: twoDaysAgo, tags: ['已验证收入', '监控', '开发者'], category: '开发者工具',
  },
  {
    id: 'ph-sample-003',
    title: 'Social Media Scheduler for Chinese Creators',
    problem: '小红书/抖音运营者每天手动在多个平台重复发布相同内容，各平台最佳发布时间不同，效率极低',
    solution: '内容一次创作，AI 自动适配各平台格式（标题/标签/比例）+最佳时间排期，数据分析各平台 ROI',
    score: 5, chinaFit: 'high', chinaReason: '国内双平台运营需求旺盛，现有工具要么太贵要么体验差，信息差明显',
    soloFit: 'maybe', soloReason: '需对接小红书/抖音 API，审核较复杂，3-6 个月完成完整版',
    techStack: ['Next.js', '小红书 API', '抖音 API', 'Supabase'], devTimeline: '3-6月',
    mvp: '先只做小红书+微博，手动一键复制内容+定时提醒，验证用户愿意付费后扩展',
    coldStart: '内容运营/MCN 微信群精准投放，找 20 个头部博主免费用换背书',
    url: 'https://www.producthunt.com', source: 'producthunt', sourceLabel: 'Product Hunt',
    dateKey: twoDaysAgo, tags: ['社交媒体', '内容运营', '效率'], category: '营销增长',
  },
];

// 合并所有数据
const allItems = [...overseasItems, ...zhihuItems].map(item => ({
  ...item,
  scoreReason: item.scoreReason || (item.mrr ? `已验证收入 ${item.mrr}` : '热门赛道'),
  tags: item.tags || [],
  fetchedAt: new Date().toISOString(),
}));

fs.writeFileSync(OUTPUT, JSON.stringify(allItems, null, 2), 'utf8');
console.log(`生成种子数据: ${allItems.length} 条 → ${OUTPUT}`);
console.log('各来源:',
  `PH: ${allItems.filter(i => i.source === 'producthunt').length}`,
  `TMRR: ${allItems.filter(i => i.source === 'trustmrr').length}`,
  `Reddit: ${allItems.filter(i => i.source === 'reddit').length}`,
  `HN: ${allItems.filter(i => i.source === 'hackernews').length}`,
  `知乎: ${allItems.filter(i => i.source === 'zhihu').length}`
);
